version: '3'

tasks:
  start-docker-dev:
    desc: Setups and starts the docker dev environment
    cmds:
      - docker compose -f frontend/docker/docker-compose.yml -p kita up -d

  stop-docker-dev:
    desc: Removes and stops the docker dev environment
    cmds:
      - docker compose -f frontend/docker/docker-compose.yml -p kita down

  clean:
    desc: Cleans the whole repository from dependencies / build files and so on
    cmds:
      - node scripts/clean.js

  install-deps:
    desc: Installs all dependencies of all workspaces (be carefull in large projects)
    cmds:
      - cd frontend;yarn install --force

  update-deps:
    desc: Updates all yarn workspace dependencies and cleans the project
    cmds:
      - node scripts/clean.js
      - node scripts/update-deps.js
