version: '3'
services:
  directus:
    container_name: kita-hoersel-dev-directus
    build: .
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/database:/directus/database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      DB_CLIENT: 'sqlite3'
      DB_FILENAME: 'database/database.sql'

      ADMIN_EMAIL: 'vscode@kita.dev'
      ADMIN_PASSWORD: 'directus'
    networks:
      - kita-hoersel-dev-network

networks:
  kita-hoersel-dev-network:
    external: true
